name: CI

on: 
  schedule:
    - cron: '45 01 30 * *'
  push:
  fork:

jobs:
  test_utils:
    name: Check utils
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Create venv
      run: python -m venv venv

    - name: Activate venv
      run: source venv/bin/activate

    - name: Cache venv
      uses: actions/cache@v4
      with:
        path: venv
        key: ${{ runner.os }}-${{ hashFiles('./utils/requirements.txt') }}

    - name: setup environment
      id: setup
      run: python -m pip install -r ./utils/requirements.txt

    - name: list packages
      id: list_pakcages
      run: python -m pip list

    - name: check utils
      id: check_utils
      run: python -m pytest --cov=utils --cov-report=term-missing -n auto ./utils/tests/

  badges:
    name: Add Google Colab Badges
    needs: test_utils
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: setup environment
      id: setup
      run: python -m pip install bs4 jupyter lxml

    - name: Add/Update badges
      id: badges
      run: python ./utils/add_colab_main_buttons.py

    - name: Commit & push
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message : "Clean ipynb ${{ github.sha }}"

  test_ipynb_colab:
    needs: badges
    name: test ipynb on Google Colab
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.12'

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Create venv
      run: python -m venv venv

    - name: Activate venv
      run: source venv/bin/activate

    - name: Cache venv
      uses: actions/cache@v4
      with:
        path: venv
        key: ${{ runner.os }}-${{ hashFiles('./requirements.txt') }}

    - name: install dependencies
      run: python -m pip install -r ./requirements.txt
    - 
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: python -m pytest -n auto -k 'not (links or update_nmisp_py)' ./tests
      